Repository tryber/sd-012-project-recipes-app, pull requests merged in 2021-09, with the labels that each got.

#860 [ Grupo 35 ] - Requisitos 52 e 53
  src/pages/RecipesInProgress/CheckList/index.js
  src/pages/RecipesInProgress/index.js
Labels: code-review

#710 [Grupo 24] [Explore Ingredients]
  package-lock.json
  src/components/DefaultComponents/Input.js
  src/components/DefaultComponents/RadiosButton.js
  src/index.css
  src/index.css.map
  src/pages/DrinksList.jsx
  src/pages/ExploreDrinksByIngredients.jsx
  src/pages/ExploreFoodByIngredients.jsx
  src/pages/MealsList.jsx
  src/redux/actions/actionAPIMeal.js
  src/redux/actions/index.js
  src/redux/reducers/reducerAPI.js
  src/styles/_ingredients.scss
Labels: merge, code-review

#865 [Grupo 24] Receitas feitas 54-56
  package-lock.json
  src/App.js
  src/_App.scss
  src/components/DefaultComponents/Button.js
  src/components/DefaultComponents/Input.js
  src/components/DefaultComponents/RadiosButton.js
  src/components/HeaderWithSearch.js
  src/components/SearchBar/ButtonSearch.js
  src/components/ShareBtn.js
  src/hooks/useIngredients.js
  src/index.css
  src/index.css.map
  src/pages/DrinksDetails.jsx
  src/pages/DrinksInProgress.jsx
  src/pages/DrinksList.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksByIngredients.jsx
  src/pages/ExploreFoodByIngredients.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodInProgress.jsx
  src/pages/MealsList.jsx
  src/pages/RecipesDone.jsx
  src/redux/actions/actionAPIMeal.js
  src/redux/actions/index.js
  src/redux/reducers/reducerAPI.js
  src/styles/_details.scss
  src/styles/_in-progress.scss
  src/styles/_ingredients.scss
  src/tests/searchBar.test.js
Labels: bug, don't merge

#899 [GRUPO-25] [TELA DE DETALHES FINALIZADA]
  src/components/componentCSS/HeaderFood.css
  src/pages/DrinkRecipeDetails.js
  src/pages/Drinks.js
  src/pages/ExploreMealsByOrigin.js
  src/pages/MealRecipeDetails.js
  src/pages/Meals.js
  src/pages/Profile.js
  src/pages/pageCSS/DrinkRecipeDetails.css
  src/pages/pageCSS/MealRecipeDetails.css
Labels: merge

#908 [ Grupo 35 ] - Requisito 39
  cypress/integration/recipe_detail_spec.js
  src/pages/DetailsPage/index.js
  src/pages/RecipesInProgress/index.js
Labels: code-review

#913 32 tests foods drinks ex foods ex drinks
  src/App.test.js
  src/tests/ExploreDrinks.test.js
  src/tests/ExploreFoods.test.js
  src/tests/MainDrinks.test.js
  src/tests/MainFoods.test.js
  src/tests/renderWithRouter.js
Labels: code-review

#902 [GRUPO 17][Tela de Receitas Feitas]
  src/components/NoRecipesDone.jsx
  src/components/RenderDrink.jsx
  src/components/RenderFood.jsx
  src/context/Provider.jsx
  src/pages/MealDetails.jsx
  src/pages/RecipesDone.jsx
  src/styles/Details.css
  src/styles/NoRecipesDone.css
  src/styles/RecipesDone.css
Labels: code-review

#934 [Grupo 35] - Explorar por ingredientes
  src/Routes.js
  src/context/DataProvider.js
  src/pages/ExploreByIngredients/index.js
  src/pages/ExploreDrinkByIngredients/index.js
  src/pages/ExploreFoodByIngredients/index.js
  src/pages/index.js
  src/services/getIngredients.js
  src/services/index.js
Labels: merge, code-review

#979 [ Grupo 35 ] - Tela de detalhes
  package-lock.json
  src/pages/DetailsPage/index.js
  src/pages/Login/index.js
  src/pages/Login/styles.css
Labels: code-review

#937 [GRUPO-25][RECIPE-PROGRESS-RAFATORANDO]
  src/App.js
  src/components/DrinkIngredientsList.jsx
  src/components/FavoriteButton.jsx
  src/components/MealsIngredientsList.jsx
  src/components/ShareButton.jsx
  src/context/MyContextProvider.js
  src/pages/DrinkProcess.js
  src/pages/DrinkProgress.js
  src/pages/DrinkRecipeDetails.js
  src/pages/Drinks.js
  src/pages/MealProcess.js
  src/pages/MealProgress.js
  src/pages/MealRecipeDetails.js
  src/pages/Meals.js
  src/tests/BottomMenu.test.js
Labels: don't merge

#888 [Grupo 9] Tela de perfil
  cypress/integration/recipes_list_spec.js
  src/Components/Card.js
  src/Pages/Bebidas.js
  src/Pages/Comidas.js
  src/Pages/Perfil.js
Labels: code-review

#1044 Main group 35 estilizacao
  src/App.js
  src/components/Footer/index.js
  src/images/leFour.svg
  src/pages/DetailsPage/detailsPage.css
  src/pages/DetailsPage/index.js
  src/pages/DoneRecipes/index.js
  src/pages/DoneRecipes/styles.css
  src/pages/DrinkExplorer/index.js
  src/pages/ExploreByIngredients/index.js
  src/pages/ExploreByLocation/HeaderLocation/DropDown/index.js
  src/pages/ExploreByLocation/HeaderLocation/DropDown/styles.css
  src/pages/ExploreByLocation/index.js
  src/pages/Explorer/index.js
  src/pages/FavoriteRecipes/index.js
  src/pages/FoodExplorer/index.js
  src/pages/Home/SearchHeader/CategoryContainer/index.js
  src/pages/Home/SearchHeader/FormFilter/index.js
  src/pages/Home/SearchHeader/FormFilter/styles.css
  src/pages/Home/index.js
  src/pages/Login/index.js
  src/pages/Login/styles.css
  src/pages/Profile/index.js
  src/pages/RecipesInProgress/index.js
  src/pages/RecipesInProgress/styles.css
  src/styles/footer.css
  src/styles/globals.css
  src/styles/header.css
Labels: code-review

#1088 [RESOLVIDO] [TELA-RECEITAS-FEITAS-QUEBRANDO]
  src/components/FavoriteButton.jsx
  src/components/SearchBar.jsx
  src/pages/DoneRecipes.js
  src/pages/DrinkProgress.js
  src/pages/Drinks.js
  src/pages/FavoriteRecipes.js
  src/pages/Login.js
  src/pages/MealProgress.js
  src/pages/Meals.js
  src/tests/BottomMenu.test.js
  src/tests/HeaderSearchBar.test.js
Labels: enhancement

#1101 [Grupo 9] - Testes para as página de detalhes de comidas e bebidas
  src/Pages/DetalheComida.js
  src/tests/DetalheBebida.test.js
  src/tests/DetalheComida.test.js
  src/tests/mocks/RecomendedDrinks.js
  src/tests/mocks/RecomendedFoods.js
  src/tests/mocks/oneMeal.js
Labels: code-review
