Repository tryber/sd-012-project-recipes-app, pull requests merged in 2021-08, with the labels that each got.

#33 [Grupo 26] [Roberval] - Começando o projeto
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/DrinkCard/index.js
  src/components/DrinkCard/style.css
  src/components/DrinkList/index.js
  src/components/FoodList/index.js
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Header/index.js
  src/components/Header/style.css
  src/components/Loading/index.js
  src/components/LoginForm/index.js
  src/components/LoginForm/style.css
  src/components/MealCard/index.js
  src/components/MealCard/style.css
  src/components/SearchBar/index.js
  src/components/SearchBar/style.css
  src/components/index.js
  src/images/loadingIcon.svg
  src/pages/DrinkRecipe.js
  src/pages/Drinks.js
  src/pages/Explore.js
  src/pages/ExploreArea.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreDrinksIngredients.js
  src/pages/ExploreFoods.js
  src/pages/ExploreFoodsIngredients.js
  src/pages/Favorites.js
  src/pages/FoodRecipe.js
  src/pages/Foods.js
  src/pages/Home.js
  src/pages/InProgressDrink.js
  src/pages/InProgressFood.js
  src/pages/Made.js
  src/pages/Profile.js
  src/pages/index.js
  src/redux/index.js
  src/redux/reducers/drinkReducer.js
  src/redux/reducers/foodReducer.js
  src/redux/reducers/index.js
  src/services/drinkAPI.js
  src/services/foodAPI.js
  src/utils/index.js
Labels: code-review

#63 [ Grupo 35 ] - Tela de Login
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/Pages/DoingDrinks/index.js
  src/Pages/DoingFoods/index.js
  src/Pages/DoneRecipes/index.js
  src/Pages/DrinkDetails/index.js
  src/Pages/DrinkExplorer/index.js
  src/Pages/Drinks/index.js
  src/Pages/ExploreByLocation/index.js
  src/Pages/ExploreDrinkByIngredients/index.js
  src/Pages/ExploreFoodByIngredients/index.js
  src/Pages/Explorer/index.js
  src/Pages/FavoriteRecipes/index.js
  src/Pages/FoodDetails/index.js
  src/Pages/FoodExplorer/index.js
  src/Pages/Foods/index.js
  src/Pages/Login/index.js
  src/Pages/Profile/index.js
  src/Routes.js
  src/index.css
  src/index.js
  src/serviceWorker.js
  src/utils/index.js
Labels: code-review

#106 [ Grupo 35 ] - Criando Header
  src/Pages/DoneRecipes/index.js
  src/Pages/DrinkExplorer/index.js
  src/Pages/Drinks/index.js
  src/Pages/ExploreByLocation/index.js
  src/Pages/ExploreDrinkByIngredients/index.js
  src/Pages/ExploreFoodByIngredients/index.js
  src/Pages/Explorer/index.js
  src/Pages/FavoriteRecipes/index.js
  src/Pages/FoodExplorer/index.js
  src/Pages/Foods/index.js
  src/Pages/Profile/index.js
  src/components/Footer/index.js
  src/components/Header/index.js
  src/components/SearchHeader/index.js
  src/styles/header.css
Labels: code-review

#17 [Grupo 24] Página de Login
  package-lock.json
  package.json
  src/App.js
  src/hooks/useLogin.js
  src/hooks/useRedirect.js
  src/hooks/useValidation.js
  src/index.js
  src/pages/Login.jsx
  src/redux/actions/index.js
  src/redux/actions/loginAction.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/store/index.js
  src/renderWithRouter.js
  src/tests/login.test.js
Labels: merge, code-review

#116 [ Grupo 35 ] - Criando Footer
  package-lock.json
  src/Pages/DrinkExplorer/index.js
  src/Pages/Drinks/index.js
  src/Pages/ExploreByLocation/index.js
  src/Pages/ExploreDrinkByIngredients/index.js
  src/Pages/ExploreFoodByIngredients/index.js
  src/Pages/Explorer/index.js
  src/Pages/FoodExplorer/index.js
  src/Pages/Foods/index.js
  src/Pages/Profile/index.js
  src/components/Footer/index.js
  src/styles/footer.css
Labels: code-review

#125 [ Grupo 26 ] [ Roberval ] - Tela de Explorar por Area
  package-lock.json
  package.json
  src/App.js
  src/components/DrinkList/index.js
  src/components/ExploreAreaComponent/index.js
  src/components/FoodList/index.js
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/MealCard/index.js
  src/components/NotFoundComponent/index.js
  src/components/SearchBar/index.js
  src/components/index.js
  src/pages/ExploreArea.js
  src/pages/NotFound.js
  src/pages/index.js
  src/services/foodAPI.js
Labels: code-review

#177 [GROUP 11] - [SCREEN-RECIPES]
  package-lock.json
  public/index.html
  public/logo512.png
  src/components/Button.js
  src/components/Card.js
  src/components/css/Card.css
  src/components/index.js
  src/pages/Drinks.js
  src/pages/Meals.js
  src/pages/Profile.js
  src/pages/css/Drinks.css
  src/pages/css/Meals.css
  src/services/api.js
Labels: code-review

#181 [ Grupo 35 ] - Tela de Perfil
  src/Pages/Profile/index.js
  src/utils/index.js
Labels: code-review

#102 [GRUPO 26] Requisitos da tela de detalhes
  src/components/DetailsButtonsField/index.js
  src/components/DrinkDetails/index.js
  src/components/DrinkDetails/style.css
  src/components/Ingredients/index.js
  src/components/MealDetails/index.js
  src/components/MealDetails/style.css
  src/components/Recommendations/index.js
  src/components/StartRecipe/index.js
  src/components/index.js
  src/pages/DrinkRecipe.js
  src/pages/FoodRecipe.js
  src/services/drinkAPI.js
  src/services/foodAPI.js
  src/utils/index.js
Labels: code-review

#178 [Grupo 14] [Requisito 25 e 26]
  src/Routes.js
  src/components/Card.js
  src/components/MenuInferior.css
  src/components/MenuInferior.js
  src/context/Provider.js
  src/index.js
  src/pages/Bebidas/index.js
  src/pages/Comidas/index.js
  src/pages/Explorar/index.js
  src/pages/Principal/index.js
  src/services/endPoints.js
  src/services/fetchApi.js
  src/services/index.js
Labels: code-review

#543 [Grupo 24] [Explore Food & Drinks]
  package-lock.json
  src/hooks/useRandom.js
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFood.jsx
  src/tests/explore-drinks.test.js
  src/tests/explore-food.test.js
  src/tests/explore.test.js
  src/tests/helpers/mocks.js
Labels: merge, code-review

#595 [GROUP 11] - [SCREEN-EXPLORE-BY-AREA]
  package.json
  src/App.js
  src/components/Button.js
  src/components/css/Card.css
  src/components/css/DoneCard.css
  src/components/index.js
  src/helpers/fomartCategoriesID.js
  src/pages/DoneRecipes.js
  src/pages/Drinks.js
  src/pages/Meals.js
  src/pages/MealsByArea.js
  src/pages/NotFound.js
  src/pages/css/DoneRecipes.css
  src/pages/css/Drinks.css
  src/pages/css/Meals.css
  src/pages/css/MealsByArea.css
  src/pages/css/NotFound.css
  src/pages/index.js
  src/services/api.js
  src/tests/DoneRecipes.test.js
  src/tests/Drinks.test.js
  src/tests/Meals.test.js
  src/tests/MealsByArea.test.js
  src/tests/helpers/renderWithRouter.js
  src/tests/mocks/categories.js
  src/tests/mocks/drinks.js
  src/tests/mocks/drinksMock.js
  src/tests/mocks/meals.js
  src/tests/mocks/mealsByAreaMock.js
  src/tests/mocks/mealsMock.js
  src/tests/mocks/recipesMock.js
Labels: code-review

#511 Main group 35 details page semi completa
  package-lock.json
  package.json
  src/App.js
  src/Routes.js
  src/components/CopyButton/index.js
  src/components/SearchHeader/CategoryContainer/index.js
  src/context/CategoriesProvider.js
  src/context/FiltersProvider.js
  src/pages/DetailsPage/ListDetails/index.js
  src/pages/DetailsPage/RecipesRecommendation/index.js
  src/pages/DetailsPage/index.js
  src/pages/DrinkDetails/index.js
  src/pages/FoodDetails/index.js
  src/pages/Home/SearchHeader/CategoryContainer/index.js
  src/pages/Home/SearchHeader/FormFilter/index.js
  src/pages/Home/SearchHeader/index.js
  src/pages/Home/index.js
  src/pages/index.js
  src/services/fetchCategories.js
  src/services/getDetails.js
  src/services/index.js
Labels: help wanted

#497 [Grupo 24] In progress recipes
  src/App.js
  src/components/ShareBtn.js
  src/pages/DrinksByOrigin.jsx
  src/pages/DrinksInProgress.jsx
  src/pages/FoodInProgress.jsx
  src/utils/clipboardCopy.js
  src/utils/fetchAPIbyID.js
Labels: merge

#622 [GROUP 11] - [TEST-EXPLORE-BY-AREA]
  src/components/Card.js
  src/context/Provider.js
  src/pages/Drinks.js
  src/pages/Meals.js
  src/pages/NotFound.js
  src/tests/Drinks.test.js
  src/tests/Meals.test.js
  src/tests/MealsByArea.test.js
  src/tests/NotFound.test.js
  src/tests/helpers/mockedFetchs.js
  src/tests/helpers/renderWithRouter.js
  src/tests/mocks/drinksMock.js
  src/tests/mocks/mealsMock.js
Labels: code-review

#585 [Group 13] Receitas Favoritas
  src/components/FavoriteRecipeCard/FavoriteRecipeCard.css
  src/components/FavoriteRecipeCard/FavoriteRecipeCard.jsx
  src/pages/Favoritas/ReceitasFavoritas.jsx
Labels: code-review

#631 [Group 13] Testes Header, SearchBar, Footer, Tela Princiapal
  src/components/RecipeCard/RecipeCard.jsx
  src/components/SearchBar/SearchBar.jsx
  src/endPoints/comidas.js
  src/setupTests.js
  src/tests/App.test.js
  src/tests/components/Footer.test.js
  src/tests/components/Header.test.js
  src/tests/components/SearchBar.test.js
  src/tests/helpers/renderWithRouterAndRedux.js
  src/tests/mocks/fecthMock.js
  src/tests/mocks/respMoks.js
  src/tests/pages/TelaPrincipal.test.js
Labels: code-review

#345 [Grupo 9] - Paginas de Detalhes de Comida e Bebida
  src/Components/RecomendedCard.js
  src/Pages/DetalheBebida.css
  src/Pages/DetalheBebida.js
  src/Pages/DetalheComida.css
  src/Pages/DetalheComida.js
  src/hooks/useIsFavorite.js
  src/service/BebidasAPI.js
  src/service/ComidasAPI.js
  src/service/getDetailsInitialButton.js
  src/service/getEmbedURL.js
  src/service/getRecipeIngredients.js
  src/service/isRecipeFavorite.js
Labels: code-review

#608 [GRUPO 26] Teste tela de receitas prontas
  package-lock.json
  package.json
  src/App.js
  src/components/DoneRecipes/index.js
  src/components/DrinkInProgress/index.js
  src/components/Ingredients/index.js
  src/components/MealInProgress/index.js
  src/components/StartRecipe/index.js
  src/pages/Done.js
  src/pages/index.js
  src/tests/doneRecipes.test.js
  src/tests/mocks/mockLocalStorage.js
  src/utils/index.js
Labels: code-review

#667 [Grupo 35] - requisitos [44 /46] e [54/59]
  package-lock.json
  src/components/CopyButton/index.js
  src/components/FavoriteButton/index.js
  src/pages/DetailsPage/ListDetails/index.js
  src/pages/DetailsPage/index.js
  src/pages/DoneRecipes/index.js
  src/pages/DoneRecipes/styles.css
  src/pages/ExploreByLocation/index.js
  src/utils/index.js
Labels: code-review

#721 [ Grupo 35 ] - Tela de Receitas Favoritas
  src/components/FavoriteButton/index.js
  src/pages/FavoriteRecipes/index.js
Labels: code-review

#708 [Grupo 24] [Bootstrap]
  package-lock.json
  src/App.js
  src/_App.scss
  src/components/DefaultComponents/Button.js
  src/components/DefaultComponents/Input.js
  src/components/DefaultComponents/RadiosButton.js
  src/components/HeaderWithSearch.js
  src/components/SearchBar/ButtonSearch.js
  src/components/ShareBtn.js
  src/hooks/useIngredients.js
  src/index.css
  src/index.css.map
  src/pages/DrinksDetails.jsx
  src/pages/DrinksInProgress.jsx
  src/pages/DrinksList.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksByIngredients.jsx
  src/pages/ExploreFoodByIngredients.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodInProgress.jsx
  src/pages/MealsList.jsx
  src/styles/_details.scss
  src/styles/_in-progress.scss
  src/styles/_ingredients.scss
Labels: merge, code-review

#652 [Grupo 16] - Eduardo - req 25 a 32
  src/components/Filter.js
  src/components/Header.js
  src/context/RecipesProvider.js
  src/services/data.js
  src/services/drinkAPI.js
  src/services/mealAPI.js
Labels: code-review

#670 [Grupo 9] - Pagina de Receitas Favoritas
  src/Components/FavoriteCards.js
  src/Pages/ReceitasFavoritas.css
  src/Pages/ReceitasFavoritas.js
Labels: code-review

#736 [GRUPO-25] [RECIPES-IN-PROGRESS]
  package.json
  src/components/Categories.jsx
  src/components/Loading.jsx
  src/components/RecomendationCard.jsx
  src/components/SearchBar.jsx
  src/context/MyContextProvider.js
  src/pages/DrinkProcess.js
  src/pages/DrinkRecipeDetails.js
  src/pages/Drinks.js
  src/pages/MealProcess.js
  src/pages/MealRecipeDetails.js
  src/pages/Meals.js
  src/pages/pageCSS/MealProcess.css
  src/pages/pageCSS/MealRecipeDetails.css
  src/services/Category/fetchCategories.js
  src/services/Header-SearchBar/Drinks/searchDrinkId.js
  src/services/Header-SearchBar/Drinks/searchDrinksByFirstLetter.js
  src/services/Header-SearchBar/Foods/searchFoodId.js
  src/services/Header-SearchBar/Foods/searchFoodsByName.js
Labels: don't merge

#807 [ Grupo 35 ] - Tela de receitas em progresso
  package-lock.json
  src/Routes.js
  src/pages/DoingDrinks/index.js
  src/pages/DoingFood/index.js
  src/pages/RecipesInProgress/CheckList/index.js
  src/pages/RecipesInProgress/CheckList/styles.css
  src/pages/RecipesInProgress/index.js
  src/pages/index.js
Labels: code-review

#821 [Group 34] Explore Local
  src/Routes.jsx
  src/pages/explore/Explore.jsx
  src/pages/explore/ExploreDrinks.jsx
  src/pages/explore/ExploreFoods.jsx
  src/pages/explore/ExploreFoodsByArea.jsx
  src/pages/notFound/NotFound.jsx
  src/services/fetchApi.js
Labels: code-review
